# .cz.yaml
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.0.1
  version_files:
    - pyproject.toml:version
  bump_message: "bump: version $current_version → $new_version"
  style:
    [
      ["qmark", "fg:#ff9d00 bold"],
      ["question", "bold"],
      ["answer", "fg:#ff9d00 bold"],
      ["pointer", "fg:#ff9d00 bold"],
      ["highlighted", "fg:#ff9d00 bold"],
      ["selected", "fg:#cc5454"],
      ["separator", "fg:#cc5454"],
      ["instruction", ""],
      ["text", ""],
      ["disabled", "fg:#858585 italic"],
    ]
  schema_pattern: "(?:feat|fix|docs|style|refactor|test|chore|build|ci|perf)(?:\\(.+\\))?!?: .+"
