"""soperes nene abajo

Revision ID: 58378ef2de5a
Revises: e82a395fdb0c
Create Date: 2024-12-19 11:58:08.821796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58378ef2de5a'
down_revision: Union[str, None] = 'e82a395fdb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_modulos',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_modulo')
    )
    op.drop_table('usuarios_modulos')
    op.add_column('modulos', sa.Column('orden', sa.Integer(), nullable=True))
    op.add_column('modulos', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modulos', 'activo')
    op.drop_column('modulos', 'orden')
    op.create_table('usuarios_modulos',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_modulo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id_modulo'], name='usuarios_modulos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='usuarios_modulos_ibfk_2'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_modulo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('roles_modulos')
    # ### end Alembic commands ###
