"""crea modelos

Revision ID: 62eeca833189
Revises: 
Create Date: 2024-12-13 17:44:04.529160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62eeca833189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=100), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('modulos',
    sa.Column('id_modulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('ruta', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_modulo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_movimiento',
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('naturaleza', sa.Enum('ENTRADA', 'SALIDA', name='naturaleza'), nullable=False),
    sa.Column('afecta_stock', sa.Boolean(), nullable=True),
    sa.Column('requiere_productos', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_movimiento'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('caja_diaria',
    sa.Column('id_caja', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('hora_apertura', sa.DateTime(), nullable=False),
    sa.Column('hora_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ventas_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_ventas_tarjeta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_ventas_transferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_pagos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_final_sistema', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_final_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadocaja'), nullable=True),
    sa.Column('id_usuario_apertura', sa.Integer(), nullable=False),
    sa.Column('id_usuario_cierre', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_apertura'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_cierre'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_caja')
    )
    op.create_table('productos_proveedores',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('es_proveedor_principal', sa.Boolean(), nullable=True),
    sa.Column('ultimo_precio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto', 'id_proveedor')
    )
    op.create_table('usuarios_modulos',
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_modulo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], )
    )
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('tipo_comprobante', sa.Enum('FACTURA', 'BOLETA', 'NOTA_CREDITO', 'RECIBO', 'INTERNO', name='tipocomprobante'), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo_entidad', sa.Enum('CLIENTE', 'PROVEEDOR', 'PUBLICO_GENERAL', name='tipoentidad'), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=True),
    sa.Column('requiere_pago_completo', sa.Boolean(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADO', 'ANULADO', name='estadomovimiento'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_caja', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_caja'], ['caja_diaria.id_caja'], ),
    sa.ForeignKeyConstraint(['id_tipo_movimiento'], ['tipos_movimiento.id_tipo_movimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('movimientos_pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'CREDITO', name='formapago'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO'), nullable=True),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimientos.id_movimiento'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('movimientos_productos',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimientos.id_movimiento'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('movimientos_stock',
    sa.Column('id_movimiento_stock', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', name='naturaleza'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimientos.id_movimiento'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_movimiento_stock')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_stock')
    op.drop_table('movimientos_productos')
    op.drop_table('movimientos_pagos')
    op.drop_table('movimientos')
    op.drop_table('usuarios_modulos')
    op.drop_table('productos_proveedores')
    op.drop_table('caja_diaria')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('tipos_movimiento')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('modulos')
    op.drop_table('imagenes')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
