"""productos, codigo barras y categorias

Revision ID: 6e4f13a2c1a7
Revises: c23ff16f5e5f
Create Date: 2024-12-04 14:22:14.519100

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e4f13a2c1a7"
down_revision: Union[str, None] = "c23ff16f5e5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
