"""add caja_diaria foreign key to egresos

Revision ID: e82a395fdb0c
Revises: 0421ea15938e
Create Date: 2024-12-17 21:19:56.279274

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e82a395fdb0c"
down_revision: Union[str, None] = "0421ea15938e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("egresos", sa.Column("id_caja", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "egresos", "caja_diaria", ["id_caja"], ["id_caja"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "egresos", type_="foreignkey")
    op.drop_column("egresos", "id_caja")
    # ### end Alembic commands ###
