"""Crea modelos

Revision ID: ee94f662f8fb
Revises: 12c7157c5037
Create Date: 2024-12-11 13:00:30.122131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee94f662f8fb'
down_revision: Union[str, None] = '12c7157c5037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria_padre', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('ruta_completa', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_padre'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias_gastos',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_documento', sa.String(length=3), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('limite_credito', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('lista_precios',
    sa.Column('id_lista', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_lista')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=50), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('limite_credito', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('tipos_gastos',
    sa.Column('id_tipo_gasto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_gasto'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('stock_actual', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('precio_costo', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('margen_ganancia', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('iva', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('cierres_caja',
    sa.Column('id_cierre', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('hora_apertura', sa.DateTime(), nullable=False),
    sa.Column('hora_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_inicial', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_ventas_efectivo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_ventas_tarjeta', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_ventas_transferencia', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_pagos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monto_final_sistema', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monto_final_real', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=True),
    sa.Column('id_usuario_apertura', sa.Integer(), nullable=True),
    sa.Column('id_usuario_cierre', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_apertura'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_cierre'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cierre')
    )
    op.create_table('codigo_barras',
    sa.Column('id_codigo_barras', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_codigo_barras'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('iva_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_compra'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('lista_precios_items',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_lista'], ['lista_precios.id_lista'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('gastos',
    sa.Column('id_gasto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_tipo_gasto', sa.Integer(), nullable=True),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.DateTime(), nullable=False),
    sa.Column('es_credito', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('comprobante', sa.String(length=100), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cierre_caja', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_gastos.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_cierre_caja'], ['cierres_caja.id_cierre'], ),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.ForeignKeyConstraint(['id_tipo_gasto'], ['tipos_gastos.id_tipo_gasto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_table('items_compra',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('iva', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('iva_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('forma_pago', sa.String(length=1), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cierre_caja', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cierre_caja'], ['cierres_caja.id_cierre'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('creditos',
    sa.Column('id_credito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('saldo_pendiente', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_credito'),
    sa.UniqueConstraint('id_venta')
    )
    op.create_table('items_venta',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('iva', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('pagos_creditos',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_credito', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_credito'], ['creditos.id_credito'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_creditos')
    op.drop_table('items_venta')
    op.drop_table('creditos')
    op.drop_table('ventas')
    op.drop_table('items_compra')
    op.drop_table('gastos')
    op.drop_table('lista_precios_items')
    op.drop_table('compras')
    op.drop_table('codigo_barras')
    op.drop_table('cierres_caja')
    op.drop_table('productos')
    op.drop_table('tipos_gastos')
    op.drop_table('proveedores')
    op.drop_table('lista_precios')
    op.drop_table('imagenes')
    op.drop_table('clientes')
    op.drop_table('categorias_gastos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
