"""crea  usuarios y roless

Revision ID: f1f9cfcb82a8
Revises: 955aaf7237e8
Create Date: 2024-12-08 18:05:24.848282

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f9cfcb82a8"
down_revision: Union[str, None] = "955aaf7237e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
